---
title: "Probability Final Exam - Fall 2024"
format: pdf
---

## Permutations and Combinations

@. A chef has 10 different herbs in their kitchen. They want to create a special blend by choosing 4 herbs, but the order in which the herbs are chosen doesn't matter. How many blends of 4 herbs can the chef create from the 10?


\



@. At a music festival, there are 7 different musicians available to perform in a specific order on stage. The organizer needs to select 3 musicians to play the first, second, and third. How many possible arrangements are there for the organizer to choose and arrange 3 musicians out of the 7?


\



@. An ecology class has 12 students, and they are creating a team of 3 students to monitor a local wetland area. The order in which members are chosen for the team doesn't matter. How many different teams of 3 students can the professor form from its 12 students?


\

\


@. COA is forming a committee to lead the design of a new arts center, which will consist of 7 members: 2 faculty members, 3 students, and 2 staff. If there are 8 faculty members, 12 students, and 8 staff available, how many ways can the committee be formed if it must include exactly 2 faculty, 3 students, and 2 staff?


{{< pagebreak >}}

## Probability Fundamentals

Consider a nine sided die (with sides 0, 1, 2, 3, 4, 5, 6, 7, 8, and 9). You roll this die once. Let:

-   A be the event that a given roll yields an even number (this includes 0).   
-   B be the event that a given roll is greater than or equal to three.   
-   C be the event that the number appears in the song title "867-5309/Jenny" by Tommy Tutone.

@. Find $\text{P}(A)$, $\text{P}(B)$ and $\text{P}(C)$

  \
  
  \
  
@. Find $\text{P}(A \cup B)$ 

  \
  
  \
  
  \
  
@. Find $\text{P}(B \cap C)$

  \
  
  \
  
  \
  
@. Find $\text{P}(A \cap B^C)$


{{< pagebreak >}}

One ticket will be drawn at random from each of the two boxes below:

\begin{center}
$A: \fbox{\fbox{0}\fbox{1} \fbox{2} \fbox{3}}$ $\hspace{1cm}$ $B: \fbox{ \fbox{2} \fbox{3} \fbox{4} \fbox{5}}$
\end{center}

@. What is the probability the number drawn from $A$ is greater than the one drawn from $B$?

   \
   
   \

@. What is the probability that the number drawn from $A$ is equal to the one drawn from $B$?

   \
   
   \

@. What is the probability the number drawn from $A$ is smaller than the one drawn from $B$?

   \
   
   \

   
@. Consider the box $\fbox{ \fbox{1} \fbox{2} \fbox{2} \fbox{3} \fbox{4}}$. I draw two tickets at random **with** replacement. If my first draw is a 2, what is the probability that my second draw is a 3?

\

\

@. Consider the box $\fbox{ \fbox{1} \fbox{2} \fbox{2} \fbox{3} \fbox{4}}$. I draw two tickets at random **without** replacement. If my first draw is a 2, what is the probability that my second draw is a 3?

{{< pagebreak >}}

@. Write the code to simulate in R choosing one ticket from the box $\fbox{ \fbox{1} \fbox{2} \fbox{2} \fbox{3} \fbox{4}}$ **without replacement**.

  \
  
  \

@. Write the code to simulate in R choosing five tickets from the box $\fbox{ \fbox{1} \fbox{2} \fbox{2} \fbox{3} \fbox{4}}$ **with replacement**.

  \
  
  \

@. Write the line of code which will ensure that you receive the same sample each time you run the code.

  \
  
  \

## Computing Probabilities

Consider picking numbers from the following box.

\begin{center}
$\fbox{\fbox{0} \fbox{1} \fbox{2} \fbox{3}}$ $\hspace{1cm}$ 
\end{center}

Let $A$ be the event that the *first pick* yields an even number; $B$ be the event that the *second pick* is greater than or equal to one. 

@. Pick two numbers without replacement. Find $\text{P}(B|\text{first pick is 0})$.

\


@. Pick two numbers without replacement. Find $\text{P}(B|\text{first pick is 2})$.

\

@. Pick two numbers with replacement. Find  $\text{P}(B|A)$.

\

\


Consider a fair, eight-sided die. 


@. I roll the die four times. What is the probability that the rolls are **not all the same** (e.g. No roll with 1, 1, 1, 1; 2, 2, 2, 2 etc.)?

\

\


@. Maganga loves to read books from two genres: mystery and science fiction*. Each time Maganga picks a book to read, they choose independently of previous choices (like a coin toss). That week, they had limited time, so they picked a book to read on only three separate days. N.B. Maganga owns no books that are both mystery and science fiction.

Define the events $A$ and $B$ where:

$A$ is the event that Maganga picked a mystery book *more than once* that week; 

$B$ is the event that the books Maganga picked that week included *both* a mystery and science fiction book.

@. Find $P(A)$, $P(B)$, $P(A \cup B)$, and $P(B \cup A)$.

\

\

\


@. Are $A$ and $B$ independent? Justify your answer with a sentence or two and refer to your work above.


\newpage


An American roulette wheel has 38 pockets, of which 18 are red, 18 black, and 2 are green. In each round, the wheel is spun and a white ball lands in one of these 38 pockets.

@. What is the probability of getting at the ball landing in a red pocket at least once in 5 spins of the wheel?

\

\

@. Write R code to simulate six spins of this wheel. 

\


## Probability Distributions

Imagine a bag with five pieces of treasure in it, three of which are emeralds (green) and one ruby (red). The treasure pieces are identical in shape and size; only their colors differ. Now suppose we draw three times at random (meaning each piece is equally likely to be drawn) from this bag. For each of the following scenarios, list all the possible outcomes, and make **a table** and sketch **a probability histogram** showing the probability distribution of these outcomes.

@. We draw *with* replacement.

\

\

\

\

@. We draw *without* replacement.

\

\

{{< pagebreak >}}

## Random Variables

For the box below, draw one ticket at random, and let $X$ be the value of the ticket that you draw. 

@. \fbox{\fbox{-2} \fbox{-1} \fbox{-1} \fbox{1} \fbox{2}}

Write down the pmf, and draw the graph of the cdf of $X$.

\

\

\


\

\

Suppose  $X \sim$ Poisson$(4)$, where $X$ represents the number of buses that arrive at a particular stop within an hour.

@. What is the probability that *no buses* arrive at the stop within the hour? After writing the expression for this probability, compute it in R using an appropriate function, and copy your code here.

\

\

\

@. What is the probability that *at least three buses* arrive at the stop within the hour? Compute the probability in R using an appropriate function, and copy your code here.


## Expectation and Variance

@. Let $X$ be a Discrete Uniform random variable on $[-3, -1, 0, 1, 4].$ Let $Y = X^2$. Find $\mathbb{E}(Y)$. 

\

\

\

Find $\mathbb{Var}(Y)$.

\

\

\

Imagine you’re tossing a basketball at a hoop 15 times, aiming to score a basket. In each attempt, there’s a probability of landing a successful shot, which depends on your skill and accuracy. You haven't been practicing basketball very much lately, so your probability of making a shot is only 30%. 

@. Let $S$ be the number of times in 15 shots that your basketball goes in the basket. Calculate $\mathbb{E}(S)$, $Var(S)$ and $SD(S)$.

\

\

\

@. Write R code which will allow you to simulate 15 shots (where your possible outcome is that you either make the shot *successful* or not *unsuccessful shot*), and count the number of successful shots.

\

\

@. Write R code which will allow you to simulate 100 of these experiments (so 100 experiments, each featuring 15 shots, and the number of successful shots is counted in each experiment). Your output should be a vector called `basketball_shots_made` with 100 observations, where the first element is the number of successful shots landed on in experiment one, and so on.

\

\


@. Write R code to calculate the mean, variance and standard deviation of the vector you created in the last step. Copy it below.

\

\



Human reaction times are often modeled with a normal distribution. For simple tasks (like pressing a button in response to a visual cue) tend to have a mean of 250 ms and a standard deviation of 50 ms.

@. Using an appropriate R function, calculate the proportion of people who have a reaction time faster than 150 ms (i.e. less than 150 ms). Next calculate the proportion of people who have a reaction time slower than 250 ms (i.e. more than 250 ms). Write the R code here.

  \
  
  \ 


@. Using an appropriate R function, generate 100 reaction times and calculate the mean and standard deviation of the vector created. Write the R code here and make sure to include code that will make your simulation repeatable.
